import type { PayloadAuthorDto } from '@/persistence/payload/types/payloadAuthor.dto'
import type { PayloadCategoryDto } from '@/persistence/payload/types/payloadCategory.dto'
import type { PayloadTagDto } from '@/persistence/payload/types/payloadTag.dto'
import type { PayloadMediaDto } from '@/persistence/payload/types/payloadMedia.dto'

// Shared by posts and pages (@payloadcms/plugin-seo's `meta` field group).
export type PayloadSeoDto = {
  title?: string | null
  description?: string | null
  image?: number | PayloadMediaDto | null
}

export type PayloadPostDto = {
  id: number
  title: string
  slug: string
  excerpt?: string | null
  // Companion HTML field generated by lexicalHTMLField() alongside the raw Lexical
  // `content` field — see BLO-76 plan decision 1. Not part of this DTO since the
  // mapper only ever reads the HTML.
  contentHtml: string
  publishedAt?: string | null
  featuredImage?: number | PayloadMediaDto | null
  author: number | PayloadAuthorDto
  categories?: (number | PayloadCategoryDto)[] | null
  tags?: (number | PayloadTagDto)[] | null
  meta?: PayloadSeoDto | null
  updatedAt: string
  _status?: 'draft' | 'published' | null
}
